
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int prCon = 33;
  public static final int tpuntoycoma = 19;
  public static final int palabra = 53;
  public static final int prHasta = 31;
  public static final int prFinMientras = 36;
  public static final int prIngresar = 20;
  public static final int tigual = 48;
  public static final int prMenorOIgual = 67;
  public static final int prEsDiferente = 62;
  public static final int prMetodo = 40;
  public static final int prFinSi = 25;
  public static final int prEsIgual = 61;
  public static final int tvariable = 49;
  public static final int prConParametros = 42;
  public static final int prFuncion = 43;
  public static final int prRetornar = 39;
  public static final int tpot = 7;
  public static final int prEjecutar = 45;
  public static final int tcadena = 50;
  public static final int prFinPara = 32;
  public static final int prBooleana = 55;
  public static final int caracter = 68;
  public static final int prMenor = 65;
  public static final int prDeLoContrario = 52;
  public static final int tcomentariovariaslineas = 18;
  public static final int prMayor = 63;
  public static final int tmayor = 16;
  public static final int prImprimir = 46;
  public static final int prVerdadero = 59;
  public static final int prImprimirNl = 47;
  public static final int tcoma = 15;
  public static final int tinterrogacioninicio = 13;
  public static final int prConValor = 22;
  public static final int pare2 = 10;
  public static final int prHastaQue = 38;
  public static final int pare1 = 9;
  public static final int EOF = 0;
  public static final int prCadena = 58;
  public static final int prEntonces = 24;
  public static final int tcomentario = 17;
  public static final int prComo = 21;
  public static final int tdiv = 5;
  public static final int prIncremental = 34;
  public static final int error = 1;
  public static final int prFloat = 64;
  public static final int prBoolean = 54;
  public static final int tnum = 2;
  public static final int prFalso = 60;
  public static final int prFinFuncion = 44;
  public static final int prSi = 23;
  public static final int prSegun = 28;
  public static final int prHacer = 29;
  public static final int trest = 3;
  public static final int prFin = 12;
  public static final int prCaracter = 56;
  public static final int tmul = 6;
  public static final int prMientras = 35;
  public static final int tinterrogacionfin = 14;
  public static final int tmod = 8;
  public static final int prFinSegun = 51;
  public static final int prInicio = 11;
  public static final int prO_Si = 26;
  public static final int prDE_LO_CONTRARIO = 27;
  public static final int prRepetir = 37;
  public static final int prMayorOIgual = 66;
  public static final int prFinMetodo = 41;
  public static final int prNumero = 57;
  public static final int tsum = 4;
  public static final int prPara = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tnum",
  "trest",
  "tsum",
  "tdiv",
  "tmul",
  "tpot",
  "tmod",
  "pare1",
  "pare2",
  "prInicio",
  "prFin",
  "tinterrogacioninicio",
  "tinterrogacionfin",
  "tcoma",
  "tmayor",
  "tcomentario",
  "tcomentariovariaslineas",
  "tpuntoycoma",
  "prIngresar",
  "prComo",
  "prConValor",
  "prSi",
  "prEntonces",
  "prFinSi",
  "prO_Si",
  "prDE_LO_CONTRARIO",
  "prSegun",
  "prHacer",
  "prPara",
  "prHasta",
  "prFinPara",
  "prCon",
  "prIncremental",
  "prMientras",
  "prFinMientras",
  "prRepetir",
  "prHastaQue",
  "prRetornar",
  "prMetodo",
  "prFinMetodo",
  "prConParametros",
  "prFuncion",
  "prFinFuncion",
  "prEjecutar",
  "prImprimir",
  "prImprimirNl",
  "tigual",
  "tvariable",
  "tcadena",
  "prFinSegun",
  "prDeLoContrario",
  "palabra",
  "prBoolean",
  "prBooleana",
  "prCaracter",
  "prNumero",
  "prCadena",
  "prVerdadero",
  "prFalso",
  "prEsIgual",
  "prEsDiferente",
  "prMayor",
  "prFloat",
  "prMenor",
  "prMayorOIgual",
  "prMenorOIgual",
  "caracter"
  };
}

